Do not rely on Podman to rebuild the bundles/IIB for clusters with hosted control planes
In Prow CI containers, it appears that Podman could not be used due to a restricted environment.
The error below was returned:
```
 [DEBUG] registry.redhat.io/rhdh/rhdh-operator-bundle@sha256:2abaeacfa8fd744579e44e4b320086a8678094dd92eb24825c05f43617384529 => quay.io/rhdh/rhdh-operator-bundle@sha256:2abaeacfa8fd744579e44e4b320086a8678094dd92eb24825c05f43617384529
time="2024-11-14T08:04:54Z" level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers"
cannot clone: Operation not permitted
Error: cannot re-exec process
```

Instead, this tries to rely on both umoci [1] and Skopeo to manipulate the
images, rebuild and repush them in
the internal cluster registry.

[1] https://github.com/opencontainers/umoci